package dev.fretflow;

import dev.fretflow.engine.FingeringEngine;
import dev.fretflow.model.InstrumentConfig;
import dev.fretflow.model.Technique;
import dev.fretflow.musicxml.MusicXmlAnnotator;
import dev.fretflow.musicxml.MusicXmlParser;
import dev.fretflow.render.TabRenderer;
import dev.fretflow.util.JsonUtil;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashSet;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

public final class AllTests {
    public static void main(String[] args) throws Exception {
        Path samplePath = Path.of("examples/mini-riff.musicxml");
        byte[] sample = Files.readAllBytes(samplePath);
        byte[] slapBassSample = Files.readAllBytes(Path.of("examples/slap-bass.musicxml"));
        parserAndChordTest(sample);
        fingeringValidityTest(sample);
        annotationAndRenderingTest(sample);
        techniqueSupportTest(slapBassSample);
        compressedMxlTest(sample);
        jsonEscapingTest();
        conversionServiceTest(sample);
        commandLineTest(samplePath);
        check(Main.VERSION.equals("1.0.1"), "unexpected application version");
        System.out.println("All FretFlow tests passed.");
    }

    private static void parserAndChordTest(byte[] sample) throws Exception {
        var score = new MusicXmlParser().parse(sample);
        check(score.title().equals("Midnight Starter Riff"), "title was not parsed");
        check(score.partName().equals("Electric Guitar"), "part name was not parsed");
        check(score.events().size() == 7, "expected seven note events");
        check(score.events().get(4).notes().size() == 3, "chord notes were not grouped");
    }

    private static void fingeringValidityTest(byte[] sample) throws Exception {
        var score = new MusicXmlParser().parse(sample);
        var instrument = InstrumentConfig.from("guitar", "standard");
        var result = new FingeringEngine().optimize(score, instrument, "beginner");
        check(result.selected().size() == score.events().size(), "every event needs a fingering");
        for (var fingering : result.selected()) {
            var strings = new HashSet<Integer>();
            for (var position : fingering.positions()) {
                check(strings.add(position.stringNumber()), "a chord reused the same string");
                int lowIndex = instrument.stringCount() - position.stringNumber();
                int playedMidi = instrument.openMidi().get(lowIndex) + position.fret();
                check(playedMidi == position.note().pitch().midi(), "fingering changed note pitch");
                check(position.fret() >= 0 && position.fret() <= 24, "fret outside valid range");
            }
        }
    }

    private static void annotationAndRenderingTest(byte[] sample) throws Exception {
        var score = new MusicXmlParser().parse(sample);
        var instrument = InstrumentConfig.from("guitar", "standard");
        var fingerings = new FingeringEngine().optimize(score, instrument, "balanced").selected();
        String annotated = new String(new MusicXmlAnnotator().annotate(score, instrument, fingerings), StandardCharsets.UTF_8);
        check(annotated.contains("<sign>TAB</sign>"), "export did not select a TAB clef");
        check(annotated.contains("<string>"), "export has no string annotations");
        check(annotated.contains("<fret>"), "export has no fret annotations");
        String tab = new TabRenderer().render(score, instrument, fingerings);
        check(tab.contains("m.1"), "ASCII TAB has no measure labels");
        check(tab.contains("Generated by FretFlow AI"), "ASCII TAB has no generator label");
    }

    private static void techniqueSupportTest(byte[] sample) throws Exception {
        var score = new MusicXmlParser().parse(sample);
        check(score.events().size() == 12, "slap-bass example should contain twelve events");
        var kinds = new HashSet<Technique.Kind>();
        score.events().forEach(event -> event.notes().forEach(note ->
                note.techniques().forEach(technique -> kinds.add(technique.kind()))));
        for (Technique.Kind kind : Technique.Kind.values()) {
            check(kinds.contains(kind), "missing parsed technique: " + kind);
        }
        check(score.events().get(6).notes().get(0).pitch() == null, "dead unpitched note gained a fake pitch");

        var instrument = InstrumentConfig.from("bass", "standard");
        var fingerings = new FingeringEngine().optimize(score, instrument, "balanced").selected();
        check(fingerings.size() == score.events().size(), "technique conversion lost events");
        check(stringFor(fingerings, 2) == stringFor(fingerings, 3), "hammer-on changed strings");
        check(stringFor(fingerings, 4) == stringFor(fingerings, 5), "slide changed strings");
        check(stringFor(fingerings, 8) == stringFor(fingerings, 9), "pull-off changed strings");
        check(stringFor(fingerings, 6) == 4, "dead note did not preserve its source string");

        String tab = new TabRenderer().render(score, instrument, fingerings);
        check(tab.contains("Techniques: S=slap/thumb"), "technique legend is missing");
        check(tab.contains("S"), "slap mark is missing from ASCII TAB");
        check(tab.contains("P"), "pop mark is missing from ASCII TAB");
        check(tab.contains("(x)"), "ghost note is missing from ASCII TAB");
        check(tab.contains("h"), "hammer-on is missing from ASCII TAB");
        check(tab.contains("p"), "pull-off is missing from ASCII TAB");
        check(tab.contains("/"), "slide is missing from ASCII TAB");
        check(tab.contains("<12>"), "harmonic is missing from ASCII TAB");

        String annotated = new String(new MusicXmlAnnotator().annotate(score, instrument, fingerings),
                StandardCharsets.UTF_8);
        check(annotated.contains("<hammer-on"), "MusicXML export lost hammer-ons");
        check(annotated.contains("<pull-off"), "MusicXML export lost pull-offs");
        check(annotated.contains("<slide"), "MusicXML export lost slides");
        check(annotated.contains("<harmonic>"), "MusicXML export lost harmonics");
        check(annotated.contains("parentheses=\"yes\""), "MusicXML export lost ghost-note notation");
        check(annotated.contains("<notehead>x</notehead>"), "MusicXML export lost dead-note notation");
    }

    private static int stringFor(java.util.List<dev.fretflow.model.Fingering> fingerings, int eventIndex) {
        return fingerings.get(eventIndex).positions().get(0).stringNumber();
    }

    private static void compressedMxlTest(byte[] sample) throws Exception {
        var zipped = new ByteArrayOutputStream();
        try (var zip = new ZipOutputStream(zipped)) {
            zip.putNextEntry(new ZipEntry("META-INF/container.xml"));
            zip.write(("<?xml version=\"1.0\"?><container><rootfiles><rootfile full-path=\"score.musicxml\"/>"
                    + "</rootfiles></container>").getBytes(StandardCharsets.UTF_8));
            zip.closeEntry();
            zip.putNextEntry(new ZipEntry("score.musicxml"));
            zip.write(sample);
            zip.closeEntry();
        }
        var score = new MusicXmlParser().parse(zipped.toByteArray());
        check(score.events().size() == 7, "compressed MXL was not parsed");
    }

    private static void jsonEscapingTest() {
        check(JsonUtil.quote("a\n\"b").equals("\"a\\n\\\"b\""), "JSON escaping is invalid");
    }

    private static void conversionServiceTest(byte[] sample) throws Exception {
        var service = new ConversionService();
        var result = service.convert(sample, new ConversionService.RequestOptions(
                "guitar", "standard", "balanced", "none", "", "", ""));
        check(result.fingerings().size() == 7, "conversion pipeline lost events");
        check(result.aiStatus().equals("Smart algorithm"), "unexpected non-AI status");
        check(result.annotatedMusicXml().length > 500, "annotated export is unexpectedly small");
    }

    private static void commandLineTest(Path samplePath) throws Exception {
        Path outputDirectory = Files.createTempDirectory("fretflow-test-");
        Path xmlOutput = outputDirectory.resolve("annotated.musicxml");
        Path tabOutput = outputDirectory.resolve("tab.txt");
        var stdout = new ByteArrayOutputStream();
        var stderr = new ByteArrayOutputStream();
        int exitCode = CliApplication.run(new String[] {
                "--input", samplePath.toString(), "--output", xmlOutput.toString(),
                "--tab", tabOutput.toString(), "--style", "beginner"
        }, new PrintStream(stdout), new PrintStream(stderr));
        check(exitCode == 0, "command-line conversion failed: " + stderr);
        check(Files.size(xmlOutput) > 500, "command-line MusicXML output is unexpectedly small");
        check(Files.readString(tabOutput).contains("Generated by FretFlow AI"), "command-line TAB output is invalid");
    }

    private static void check(boolean condition, String message) {
        if (!condition) throw new AssertionError(message);
    }
}
