package dev.fretflow.render;

import dev.fretflow.model.Fingering;
import dev.fretflow.model.InstrumentConfig;
import dev.fretflow.model.NoteEvent;
import dev.fretflow.model.ParsedScore;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public final class TabRenderer {
    private static final int MEASURES_PER_BLOCK = 4;

    public String render(ParsedScore score, InstrumentConfig instrument, List<Fingering> fingerings) {
        Map<String, List<Integer>> byMeasure = new LinkedHashMap<>();
        for (int i = 0; i < score.events().size(); i++) {
            byMeasure.computeIfAbsent(score.events().get(i).measure(), ignored -> new ArrayList<>()).add(i);
        }
        var output = new StringBuilder();
        output.append(score.title()).append(" — ").append(instrument.name()).append('\n');
        output.append("Generated by FretFlow AI\n\n");

        var entries = new ArrayList<>(byMeasure.entrySet());
        for (int start = 0; start < entries.size(); start += MEASURES_PER_BLOCK) {
            int end = Math.min(entries.size(), start + MEASURES_PER_BLOCK);
            for (int stringNumber = 1; stringNumber <= instrument.stringCount(); stringNumber++) {
                final int renderedString = stringNumber;
                String label = instrument.labels().get(instrument.stringCount() - stringNumber);
                output.append(String.format("%2s|", label));
                for (int m = start; m < end; m++) {
                    for (int eventIndex : entries.get(m).getValue()) {
                        var fingering = fingerings.get(eventIndex);
                        String value = fingering.positions().stream()
                                .filter(p -> p.stringNumber() == renderedString)
                                .map(p -> String.valueOf(p.fret()))
                                .findFirst().orElse("-");
                        output.append('-').append(pad(value, 2)).append('-');
                    }
                    output.append('|');
                }
                output.append('\n');
            }
            output.append("    ");
            for (int m = start; m < end; m++) {
                int width = entries.get(m).getValue().size() * 4 + 1;
                output.append(center("m." + entries.get(m).getKey(), width));
            }
            output.append("\n\n");
        }
        return output.toString();
    }

    private String pad(String value, int width) {
        return value.length() >= width ? value : value + " ".repeat(width - value.length());
    }

    private String center(String value, int width) {
        if (value.length() >= width) return value.substring(0, width);
        int left = (width - value.length()) / 2;
        return " ".repeat(left) + value + " ".repeat(width - value.length() - left);
    }
}
