package dev.fretflow.render;

import dev.fretflow.model.Fingering;
import dev.fretflow.model.InstrumentConfig;
import dev.fretflow.model.NoteEvent;
import dev.fretflow.model.ParsedScore;
import dev.fretflow.model.ScoreNote;
import dev.fretflow.model.Technique;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public final class TabRenderer {
    private static final int MEASURES_PER_BLOCK = 4;
    private static final int TOKEN_WIDTH = 5;

    public String render(ParsedScore score, InstrumentConfig instrument, List<Fingering> fingerings) {
        Map<String, List<Integer>> byMeasure = new LinkedHashMap<>();
        for (int i = 0; i < score.events().size(); i++) {
            byMeasure.computeIfAbsent(score.events().get(i).measure(), ignored -> new ArrayList<>()).add(i);
        }
        var output = new StringBuilder();
        output.append(score.title()).append(" — ").append(instrument.name()).append('\n');
        output.append("Generated by FretFlow AI\n");
        if (hasTechniques(score)) {
            output.append("Techniques: S=slap/thumb  P=pop  x=dead  (x)=ghost  h=hammer-on  p=pull-off  /=slide  <>=harmonic\n");
        }
        output.append('\n');

        var entries = new ArrayList<>(byMeasure.entrySet());
        for (int start = 0; start < entries.size(); start += MEASURES_PER_BLOCK) {
            int end = Math.min(entries.size(), start + MEASURES_PER_BLOCK);
            for (int stringNumber = 1; stringNumber <= instrument.stringCount(); stringNumber++) {
                final int renderedString = stringNumber;
                String label = instrument.labels().get(instrument.stringCount() - stringNumber);
                output.append(String.format("%2s|", label));
                for (int m = start; m < end; m++) {
                    for (int eventIndex : entries.get(m).getValue()) {
                        var fingering = fingerings.get(eventIndex);
                        String value = fingering.positions().stream()
                                .filter(p -> p.stringNumber() == renderedString)
                                .map(p -> renderToken(p.note(), p.fret(), score))
                                .findFirst().orElse("");
                        output.append('-').append(pad(value, TOKEN_WIDTH)).append('-');
                    }
                    output.append('|');
                }
                output.append('\n');
            }
            output.append("    ");
            for (int m = start; m < end; m++) {
                int width = entries.get(m).getValue().size() * (TOKEN_WIDTH + 2) + 1;
                output.append(center("m." + entries.get(m).getKey(), width));
            }
            output.append("\n\n");
        }
        return output.toString();
    }

    private boolean hasTechniques(ParsedScore score) {
        return score.events().stream().flatMap(event -> event.notes().stream())
                .anyMatch(note -> !note.techniques().isEmpty());
    }

    private String renderToken(ScoreNote note, int fret, ParsedScore score) {
        String value;
        if (note.hasTechnique(Technique.Kind.GHOST_NOTE)) {
            value = "(x)";
        } else if (note.hasTechnique(Technique.Kind.DEAD_NOTE)) {
            value = "x";
        } else if (note.hasTechnique(Technique.Kind.HARMONIC)) {
            value = "<" + fret + ">";
        } else {
            value = String.valueOf(fret);
        }

        if (note.hasTechnique(Technique.Kind.SLAP)) value = "S" + value;
        if (note.hasTechnique(Technique.Kind.POP)) value = "P" + value;
        if (starts(note, Technique.Kind.HAMMER_ON)) value += "h";
        if (starts(note, Technique.Kind.PULL_OFF)) value += "p";
        if (starts(note, Technique.Kind.SLIDE)) value += slideSymbol(note, score);
        return value;
    }

    private boolean starts(ScoreNote note, Technique.Kind kind) {
        return note.techniques().stream().anyMatch(technique ->
                technique.kind() == kind && technique.phase() == Technique.Phase.START);
    }

    private String slideSymbol(ScoreNote note, ParsedScore score) {
        Technique start = note.techniques().stream().filter(technique ->
                technique.kind() == Technique.Kind.SLIDE && technique.phase() == Technique.Phase.START)
                .findFirst().orElse(null);
        if (start == null || note.pitch() == null) return "/";
        for (NoteEvent event : score.events()) {
            for (ScoreNote candidate : event.notes()) {
                boolean matchingStop = candidate.techniques().stream().anyMatch(technique ->
                        technique.kind() == Technique.Kind.SLIDE && technique.phase() == Technique.Phase.STOP
                                && technique.number() == start.number());
                if (matchingStop && candidate.pitch() != null) {
                    return candidate.pitch().midi() < note.pitch().midi() ? "\\" : "/";
                }
            }
        }
        return "/";
    }

    private String pad(String value, int width) {
        return value.length() >= width ? value : value + " ".repeat(width - value.length());
    }

    private String center(String value, int width) {
        if (value.length() >= width) return value.substring(0, width);
        int left = (width - value.length()) / 2;
        return " ".repeat(left) + value + " ".repeat(width - value.length() - left);
    }
}
